length_per_zone = [0.1, 9.9]
cells_per_zone = [2000, 500]
total_cross_section = [100.0, 100.0]
scattering_cross_section = [100.0, 100.0]
source = [0.0, 0.0]
inflow_value = [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]
number_of_directions = 8
iter_max = 1000000
tol = 1e-8
tau_ap = true
use_dsa = true